services:
  - type: web
    name: paladin-linux-sandbox
    runtime: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /health
    buildCommand: "echo Building sandbox..." 
    startCommand: "bash /start.sh"
    envVars:
      - key: DISPLAY
        value: :0
      - key: VNC_PORT
        value: 5900
      - key: NOVNC_PORT
        value: 6080
      - key: API_PORT
        value: 8080
    # Expose both API and VNC ports
    # Note: Render will assign a single public port, but internal services can use multiple ports
